# Generated by Django 4.0.1 on 2022-01-23 22:45

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=128)),
                ('admin', models.CharField(max_length=50)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('team_id', django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['name', 'creation_time'], primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=64, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['display_name', 'creation_time'], primary_key=True, serialize=False, unique=True)),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='Users.team')),
            ],
        ),
    ]
