# Generated by Django 4.0.1 on 2022-01-23 22:45

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=128)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('board_id', django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['name', 'creation_time'], primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=6)),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board', to='Users.team')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=128)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('task_id', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'creation_time'])),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=12)),
                ('board', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='Projects.projectboard')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.user')),
            ],
        ),
    ]
