# Generated by Django 4.0.1 on 2022-01-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_team'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='assigned_team_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='team id'),
        ),
        migrations.AddField(
            model_name='task',
            name='userid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='creation_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='team',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board', to='Users.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='Projects.projectboard'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.team'),
        ),
    ]
