# Generated by Django 4.0.1 on 2022-01-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_projectboard_assigned_team_id_task_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='userid',
            new_name='team_id',
        ),
    ]
