# Generated by Django 4.0.1 on 2022-01-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_rename_userid_task_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='assigned_team_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Team ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='User ID'),
        ),
    ]
