# Generated by Django 4.0.1 on 2022-01-26 03:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_alter_projectboard_assigned_team_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['title', 'creation_time'], primary_key=True, serialize=False),
        ),
    ]
